# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "rhode-island"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

# Pages Build Output Directory
pages_build_output_dir = ".vercel/output/static"

# Observability
[observability]
enabled = true
