# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "rhode-island"
compatibility_date = "2025-02-04"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "rhode-island-db"
database_id = "dd17504c-861a-4feb-8392-7bb34f16b56f"
