# Top-level configuration
name = "rhode-island"
compatibility_date = "2022-07-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[[d1_databases]]
binding="DB"
database_name="rhode-island"
database_id="9593f8cc-b783-4bb5-ac70-b0721059e459"
migrations_dir="./lib/db/migrations"
